language: go

go:
- 1.x

jobs:
  include:
    - stage: GitHub Release
      script: 
        - echo "Building and Deploying to GitHub releases ..."
        - go build
        - GOOS=windows GOARCH=386 go build
        - find .
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file:
          - "golkv373"
          - "golkv373.exe"
        on:
          tags: true

